### PR TITLE
cargo fmt

### PR DESCRIPTION
**Pull request by Rustin-Liu**
use cargo fmt command format code.

### CODE REVIEW

**Comment by Rustin-Liu** [comment]
I think we can use cargo fmt format our code.
It can help us keep our code style identical.

**Comment by MitMaro** [comment]
Hey @Rustin-Liu !

Can you try running format with nightly? The current format rules require a nightly build.

I think you will find that the current `master` branch is already formatted correctly when you run against nightly.

There's a script (`./scripts/format.bash`) that runs format with nightly.

**Comment by Rustin-Liu** [comment]
> Hey @Rustin-Liu !
> 
> Can you try running format with nightly? The current format rules require a nightly build.
> 
> I think you will find that the current `master` branch is already formatted correctly when you run against nightly.
> 
> There's a script (`./scripts/format.bash`) that runs format with nightly.

Hi @MitMaro !
I do not check the scripts, so I don't know need to run format with nightly.
So, I add some format setup in readme.

**Comment by MitMaro** [comment]
The failed build seems to be a TravisCI issue. I've restarted the last job to see if it picks up the new commit, but I doubt it will.

Since this is README update, I'm okay merging without the passing build.

Thanks @Rustin-Liu !

**Pull request merged**
