### PR TITLE
Add instructions for installing on Arch

### PR DESCRIPTION
**Pull request by DanielPower**
Checks a box on #172 
I started making the package, then realized someone had already done it back in March. It is slightly out of date, it points to the 1.0.0 release. I've marked the package as outdated. If the maintainer doesn't update soon, I'll make a request to take over maintainership.

### CODE REVIEW

**Comment by MitMaro** [comment]
Awesome thanks! The failing build is on my end and not with your PR, I can take care of that part.

**Comment by MitMaro** [comment]
@DanielPower mind rebasing against the latest master? That should fix the build. :)

**Comment by DanielPower** [comment]
Should be good now.

**Comment by MitMaro** [comment]
Merged, thanks @DanielPower !

**Pull request merged**
