### PR TITLE
Implement #60 (shell out to editor) + misc changes

### PR DESCRIPTION
**Pull request by nickolay**
This PR contains two minor standalone changes (the first two commits - 16adaf96f78c035776cd88778aa97d2b7981b185 and 4e33f1c2c3c2feb3682ad7d8384bb8989227827a) and a possible solution to #60 (the rest of commits). I would appreciate some feedback on this.

I was unsure which data should be stored in what object, so I simply added `comment_char` and `editor` to both `GitConfig` and `Config`, and made `GitInteractive::write_file()` return the path to the file written (so that it could be handed to the external editor). It doesn't feel ideal, but I'm not sure what would be better.

I didn't write tests because I wanted to get some feedback first (and perhaps any ideas on what you think should be minimally tested).

I tried to document the changes in commit messages and left 3 TODO markers throughout the code.

Let me know what you think!

### CODE REVIEW

**Comment by MitMaro** [comment]
Sorry for the delay in a proper review, it's been a busy few weeks for me. I'm good with the PR as is stands. Some tests would be really nice to have, but I think they would be difficult to create and I really want to get this in.

Initially `GitConfig` was supposed to represent the git configuration files, and `Config` would represent the configuration for the tool. But that distinction doesn't make a whole lot of sense, and they could easily be merged into a single struct.

I agree with your TODOs, but they can be addressed outside of this PR.

**Comment by MitMaro** [comment]
There are a few linting errors caused by my recent update to Clippy. I can handle this later if you don't get to them first. I also resolved the conflicts with GitHub, which created a merge commit. Feel free to remove that merge, and do a rebase against master.

**Comment by nickolay** [comment]
Thanks for your comments! I made the changes Clippy was suggesting and rebased.

**Comment by MitMaro** [comment]
Thanks for the great additions! :tada:

**Pull request merged**
