### PR TITLE
Add ignore blank lines option

### LINKED ISSUE #581: Support "ignore blank lines" in diff
https://github.com/rust-lang/git2-rs/pull/753 added the option to ignore blank lines when generating a diff. This should be supported.

This is currently blocked by rust-lang/git2-rs#746, since it's not possible to upgrade git2-rs without breaking the build in some systems.

### PR DESCRIPTION
**Pull request by Agreon**
closes #581

### CODE REVIEW

**Comment by Agreon** [comment]
@MitMaro I'm not sure about why the formatter changed these unrelated lines. I can fix that of course, if you say so ;)

**Comment by MitMaro** [comment]
> @MitMaro I'm not sure about why the formatter changed these unrelated lines. I can fix that of course, if you say so ;)

Thanks for the PR! Looks good, besides the random formatting problems. That might be because of running stable vs nightly Rust. Sadly, rustfmt has a number of things that don't work on stable.

For testing, if you run `cargo make dev`, it will run through all the same steps that CI runs. It will ensure that the various steps are run on stable/nightly as needed. Just a note, it will update your stable and nightly Rust versions.

**Comment by MitMaro** [comment]
Looks like there is one last formatting issue, but otherwise looks good.

Can you rebase and squash your commits together along with the remaining formatting issue? That should fix the failing linting issues as well.

Otherwise, I looked at the change, and it looks good. Thanks for the doc and test updated!

**Comment by Agreon** [comment]
@MitMaro Good thing i have a tool for that ;). With regard to the formatting: It seems like this one error comes from a unrelated library?

**Comment by MitMaro** [comment]
> @MitMaro Good thing i have a tool for that ;).

I had a genuine chuckle at that one! 😆 

> With regard to the formatting: It seems like this one error comes from a unrelated library?

You are correct that it's coming from a seemingly unrelated library. There is a [bug in rustfmt](https://github.com/rust-lang/rustfmt/issues/4968) that causes rustfmt to panic/crash when it encounters a long line. The crash is partially caused by a bug in [annotate-snippets-rs](https://github.com/rust-lang/annotate-snippets-rs/issues/25).

What is happening in this PR, is that the `#[case...]` lines are too long, and it causes rustfmt to panic when it reaches those lines. Sadly, this also means that they need to be manually formatted, and rustfmt can't fix the problem.

**Comment by MitMaro** [comment]
Thanks for implementing the new option and putting in the effort to get things through the formatter!

I'm uncertain if you're participating in [Hacktoberfest](https://hacktoberfest.com/), but if you are, the PR should be included in your contributions. If not, please let me know, and I will make sure it is.

**Pull request merged**
